<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [

            [
                'name' => 'Mariposa Corset Gown',
                'description' => 'A modern, clean-lined ballgown made of smooth satin. It features a visible corset bodice with exposed boning and a pleated bust cup. The waist is cinched tightly, flowing into a massive, unembellished skirt. Styled with a whimsical butterfly-embellished veil.',
                'price' => 58000.00,
                'material' => 'Premium Mikado Silk or Satin, Boning, Soft Tulle',
                'image' => 'd1.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => 'Enchanted Flora Gown',
                'description' => 'A romantic off-shoulder gown featuring 3D floral and feathery accents along the neckline. The corset bodice is embellished with a central jeweled motif. The skirt is voluminous and crafted from sequined fabric that catches the light, giving an ethereal glow.',
                'price' => 72000.00,
                'material' => 'Premium Mikado Silk or Satin, Boning, Soft Tulle',
                'image' => 'd2.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => 'Modern Muse Asymmetrical Gown',
                'description' => 'A sophisticated satin gown with a contemporary edge. It features an asymmetrical, pleated off-shoulder neckline that wraps around the bodice. A cluster of 3D white roses adorns the waist/hip area, serving as the focal point before the skirt flows down in soft pleats.',
                'price' => 48000.00,
                'material' => 'Soft Bridal Satin, 3D Fabric Roses, Pearl accents.',
                'image' => 'd3.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => 'Celestia Royal Ballgown',
                'description' => 'A majestic satin ballgown featuring a plunging V-neckline and long sleeves. The dress is defined by intricate silver crystal embroidery that cascades from the shoulders and bodice down to the upper skirt, creating a dramatic "raining jewels" effect against the smooth white fabric.',
                'price' => 85000.00,
                'material' => 'Heavy Duchess Satin, Swarovski-style crystals, Silver metallic thread, Structure netting.',
                'image' => 'd4.jpg',
                'category' => 'dresses',
                'stock' => 20,
            ],
            [
                'name' => 'Anastasia Gem Gown',
                'description' => 'A fairy-tale ballgown with draped, off-shoulder sleeves made of pleated tulle. The bodice features a deep basque waistline and is densely packed with heavy crystal and rhinestone beadwork in an ornate pattern. The skirt is made of shimmering sparkle tulle.',
                'price' => 95000.00,
                'material' => 'Rhinestones, Glass Beads, Sparkle Tulle, stiffened Horsehair Braid (hem).',
                'image' => 'd5.jpg',
                'category' => 'dresses',
                'stock' => 20,
            ],
            [
                'name' => 'Seraphina Glitter Gown',
                'description' => 'A sparkling princess-cut gown featuring a strapless sweetheart bodice with an overlay of high-neck illusion mesh. The neckline is adorned with a floral "necklace" effect using appliqué and strung pearls. The entire dress is constructed from glitter tulle and heavily embellished with sequins.',
                'price' => 65000.00,
                'material' => 'Glitter Tulle, Lace Appliqué, Seed Pearls, Sequins, Illusion Mesh.',
                'image' => 'd6.jpg',
                'category' => 'dresses',
                'stock' => 50,
            ],
            [
                'name' => 'Pearl Labyrinth Gown',
                'description' => 'A unique couture piece featuring a high-neck illusion yoke created entirely of strung pearls in a spiderweb/geometric pattern. It has cold-shoulder illusion sleeves and a fully beaded corset bodice that transitions into a voluminous, sparkling skirt.',
                'price' => 88000.00,
                'material' => 'Strung Pearls, Silver Beads, Illusion Netting, Glitter Tulle.',
                'image' => 'd7.jpg',
                'category' => 'dresses',
                'stock' => 10,
            ],
            [
                'name' => 'Victorian Luxe Gown',
                'description' => 'A vintage-inspired masterpiece with a high collar and long sleeves. The bodice features visible corset channels and is completely encrusted with pearls and clear sequins. It features structured ruffles at the hips, giving it a grand, royal silhouette.',
                'price' => 105000.00,
                'material' => 'Chantilly Lace, Seed Pearls, Clear Sequins, Corset Boning.',
                'image' => 'd8.jpg',
                'category' => 'dresses',
                'stock' => 10,
            ],
            [
                'name' => 'Cathedral Empress Gown',
                'description' => 'An incredibly intricate gown featuring a high illusion neckline and long sleeves. The silhouette includes a dramatic tiered "peplum" ruffle at the hips, adding volume before flowing into a full skirt. The dress is heavily encrusted with botanical embroidery and beadwork throughout the center panel.',
                'price' => 110000.00,
                'material' => 'French Lace, Organza, Crystal Beads, Tulle layers.',
                'image' => 'd9.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => 'Julianna Tiered Gown',
                'description' => 'A playful yet elegant gown featuring a sweetheart corset bodice with beaded detailing. The standout feature is the skirt, which is composed of asymmetrical, horsehair-trimmed layers (tiers) that add movement and architectural volume.',
                'price' => 68000.00,
                'material' => 'Glitter Tulle, Horsehair trim, Crystal beads, Satin lining.',
                'image' => 'd12.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],




            [
                'name' => '"Garden Muse" Draped Gown',
                'description' => 'A whimsical bohemian-style dress featuring off-shoulder draped sleeves and a sweetheart neckline. The bodice is heavily textured with lace, while the skirt features soft layers of tulle and chiffon that create a dreamy, flowing silhouette.',
                'price' => 38000.00,
                'material' => 'Silk Chiffon, Guipure Lace, Soft Tulle.',
                'image' => 'pp-4.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],

            [
                'name' => '"Secret Garden" Backless Gown',
                'description' => 'A delicate A-line gown highlighting a soft, romantic back profile. It features off-shoulder lace sleeves and a semi-sheer bodice. The skirt is made of layers of tulle with scattered floral lace patches that look as if they are floating on the fabric.',
                'price' => 42000.00,
                'material' => 'Illusion Tulle, Embroidered Lace patches.',
                'image' => 'pp-7.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],

            [
                'name' => '"Sculptured Bow" Satin Gown',
                'description' => 'A high-fashion, architectural gown defined by clean lines and luster. The back features a massive, structured bow that trails into a long, dramatic train. The fabric is smooth and unadorned by lace, relying on the sheen of the material and the dramatic silhouette to make a statement.',
                'price' => 65000.00,
                'material' => 'Silk Taffeta or Premium Satin, Horsehair braid (for hem structure).',
                'image' => 'pp-10.webp',
                'category' => 'dresses',
                'stock' => 100,
            ],

            [
                'name' => 'Pearlescent Whisper',
                'description' => 'A romantic, vintage-inspired veil that features a delicate floral lace edge adorned with scattered faux pearls. The lace frames the face softly, tapering down into a sheer illusion tulle that allows light to pass through beautifully. Ideally worn as a mantilla or capped style for a timeless, ethereal look.',
                'price' => 4500.00,
                'material' => 'Soft Illusion Tulle, Alençon Lace Trim, Faux Pearls, Clear Thread.',
                'image' => 'v1.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Royal Cathedra',
                'description' => 'Designed for a dramatic entrance, this cathedral-length veil features intricate lace appliqués that climb from the hemline upwards. The lace is embedded with subtle clear sequins that catch the light, creating a shimmering effect that complements heavily beaded gowns..',
                'price' => 8200.00,
                'material' => 'Cathedral-grade Tulle, Sequin-embellished Lace, Embroidery Thread.',
                'image' => 'v2.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Starlight',
                'description' => 'A high-glamour veil designed to complement sparkling tiaras and crystal-encrusted gowns. Made from ultra-sheer "diamond white" tulle, it features a raw or pencil edge to keep the focus on the bride’s accessories. The fabric has a subtle natural shimmer that mimics a starry night.',
                'price' => 3800.00,
                'material' => 'Diamond White Tulle, Shimmer Nylon Blend, Metal Comb.',
                'image' => 'v3.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Celestial',
                'description' => 'A show-stopping piece for the maximalist bride. This veil is densely scattered with crystals, beads, and sequins from the crown to the hem, creating a "raining light" effect. It provides medium coverage and pairs perfectly with fully sequined ballgowns.',
                'price' => 9500.00,
                'material' => 'Glitter Tulle, Swarovski Crystals, Glass Beads, Silver Sequins.',
                'image' => 'v4.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Botanical Drift',
                'description' => 'A nature-inspired chapel-length veil featuring floating lace motifs. Instead of a solid border, organic leaf and vine appliqués are hand-placed along the edges and scattered upward, creating a seamless transition between the dress and the veil.',
                'price' => 6000.00,
                'material' => 'Soft Netting, Guipure Lace Appliqués, Invisible Thread.',
                'image' => 'v5.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Grand Scallop',
                'description' => 'The definition of bridal grandeur. This extra-wide cathedral veil features a massive, scalloped lace border with bold floral patterns. The weight of the lace ensures the veil spreads wide as you walk, creating the perfect "sweeping" photo opportunity.',
                'price' => 10500.00,
                'material' => 'English Net, Heavy Chantilly Lace Border, Satin Stitch Embroidery.',
                'image' => 'v6.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Seville',
                'description' => 'A traditional Spanish-style mantilla veil characterized by its thick, continuous lace edge. It is designed to be worn over the head to frame the face in a halo of intricate embroidery. The lace features dense floral patterns that provide stunning contrast against the skin.',
                'price' => 7800.00,
                'material' => 'French Lace, Soft Tulle, Cotton Embroidery Thread.',
                'image' => 'v7.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Duchessr',
                'description' => 'Elegant and poised, this veil features a medium-width lace border with classic rose motifs. The lace is concentrated around the shoulders and elbows, adding texture to the bridal silhouette without overwhelming the bodice of the gown.',
                'price' => 5200.00,
                'material' => 'Bridal Illusion Tulle, Corded Lace Trim.',
                'image' => 'v8.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Cloud Nine',
                'description' => 'A modern, voluminous veil adorned with 3D fabric flowers and petals. The clusters of blooms are concentrated at the crown and fade downward, creating a whimsical, garden-fairy aesthetic. Perfect for spring weddings and outdoor ceremonies.',
                'price' => 6800.00,
                'material' => 'Organza (for flowers), Tulle, Seed Beads (centers of flowers).',
                'image' => 'v9.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],
            [
                'name' => 'Wildflower',
                'description' => 'A unique veil featuring patches of floral embroidery scattered across the fabric rather than just on the edge. It includes soft vine and leaf details that appear to "grow" down the back of the bride. The tulle is extremely soft, allowing for a beautiful drape over ballgowns.',
                'price' => 5900.00,
                'material' => 'Soft Mesh Tulle, Rayon Embroidery Thread, Clear Sequins.',
                'image' => 'v10.jpg',
                'category' => 'veils',
                'stock' => 100,
            ],

            [
                'name' => '"Pearl Luxe" Bridal Flat Lay',
                'description' => 'A curated luxury ensemble featuring designer footwear and matching accessories. The focal point is a pair of white satin Jimmy Choo heels adorned with all-over pearl embellishments and a large center pearl toe accent. Accompanied by a matching pearl-encrusted hard-shell clutch, velvet ring boxes, and gold-rimmed trinket dish.',
                'price' => 85593.50,
                'material' => 'Satin, leather (soles), faux pearls, gold-tone hardware, velvet (ring boxes).',
                'image' => 'a1.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Heirloom Blush" Jewel Bouquet',
                'description' => 'A stunning, everlasting bridal bouquet designed for maximum opulence. This piece features soft blush-pink silk roses densely packed and interspersed with sprays of gold filigree, clusters of faux pearls, and champagne-colored crystal branches. It is a statement piece that blends floral romance with jewelry-like structure.',
                'price' => 10920.55,
                'material' => 'High-grade silk satin roses, gold-tone craft wire, faux pearls (various sizes), champagne crystal beads, satin ribbon handle.',
                'image' => 'a2.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Cascading Brilliance" Drop Earrings',
                'description' => 'Dramatic statement earrings focusing on light refraction. A floral cluster stud connects to a marquise link, ending in a massive, solitaire pear-cut stone. These are designed to mimic high-carat diamond jewelry.',
                'price' => 5607.85,
                'material' => 'White gold vermeil, 5A Cubic Zirconia (Diamond Simulant).',
                'image' => 'a3.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Midnight Gala" Marquise Suite',
                'description' => 'A complete four-piece evening jewelry set (Necklace, Bracelet, Earrings, Ring). The design utilizes a classic "tennis" style construction but with marquise and pear-cut stones arranged in a floral-geometric pattern. It offers a diamond-like shine suitable for black-tie events.',
                'price' => 9739.95,
                'material' => 'Platinum-plated sterling silver, high-grade clear Cubic Zirconia.',
                'image' => 'a4.webp',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Maharani" Emerald & Polki Set',
                'description' => 'A magnificent South Asian bridal heritage set. This heavy, multi-layered necklace features a choker and a long "rani haar" (queen necklace). It showcases the "Polki" (uncut diamond)aesthetic set in antique gold, heavily stranded with emerald-green tumble beads and finished with lustrous pearl drops.',
                'price' => 32466.50,
                'material' => 'Antique gold-plated brass alloy, Kundan/Polki stones (glass or uncut simulants), synthetic emerald beads, cultured pearl clusters.',
                'image' => 'a5.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Frostfall" Crystal Choker',
                'description' => 'A modern, high-glamour choker designed to mimic the intricacies of lace. The piece features an elaborate web of silver filigree completely encrusted with small round crystals, dripping into larger pear-cut teardrops that create a waterfall effect on the collarbone. Matches perfectly with the included chandelier earrings.',
                'price' => 12986.60,
                'material' => 'Rhodium-plated alloy (silver tone), AAA Cubic Zirconia or Swarovski crystals.',
                'image' => 'a6.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Golden Rose" Heritage Choker',
                'description' => 'A regal choker set with a warm gold finish. The design features intricate floral cut-outs layered with clear stones. The bottom tier features a fringe of soft pink beads/pearls that add a romantic blush tone to the heavy gold structure. Includes matching heavy earrings and wrist accessories.',
                'price' => 22431.40,
                'material' => 'Gold-plated copper, clear Zircon stones, pastel pink glass beads/faux pearls.',
                'image' => 'a7.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Autumn Glow" Botanical Headpiece',
                'description' => 'A bohemian-inspired hairpiece featuring a nature motif. Gold wire stems branch out into metallic gold leaves, small white blossoms, and opal-like crystals that catch the light with a soft iridescence. Perfect for rustic or outdoor weddings.',
                'price' => 2656.35,
                'material' => 'Gold-tone wire, opalite crystals, metal leaf charms, enamel flowers.',
                'image' => 'a8.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Silver Laurel" Half-Halo',
                'description' => 'A structured yet flexible hair accessory designed to sit at the back of the head or crown. It creates a "V" shape with symmetrical branches of marquise-cut crystals forming a laurel leaf pattern. Elegant, understated, and timeless.',
                'price' => 3836.95,
                'material' => 'Silver-tone metal alloy, clear crystal rhinestones.',
                'image' => 'a9.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => '"Ethereal Breath" Hair Vine',
                'description' => 'A delicate and flexible hair vine designed to be woven into braids or updos. Inspired by "Baby Breath" flowers, it features fine silver wiring twisted into sprigs of tiny pearls and micro-crystals, creating a floating, starry effect in the hair.',
                'price' => 3246.65,
                'material' => 'Flexible silver-tone craft wire, freshwater pearls, glass seed beads.',
                'image' => 'a10.jpg',
                'category' => 'accessories',
                'stock' => 100,
            ],
            [
                'name' => 'Celestial Lace Bride',
                'description' => 'An ethereal floor-length bridal robe featuring a sheer tulle body with intricate floral lace appliqué adorning the bodice and sleeves. It creates a "barely there" illusion with a romantic, flowing silhouette perfect for pre-wedding photoshoots.',
                'price' => 5800.00,
                'material' => 'Soft Illusion Tulle, French Lace Appliqué, Satin Piping.',
                'image' => 'r1.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Swan Lake Boudoir Set',
                'description' => 'A luxurious two-piece set featuring a mini slip dress and a sheer floor-length outer robe. The robe is trimmed with plush feathers along the hem and cuffs, adding dramatic movement and texture.',
                'price' => 6500.00,
                'material' => 'Sheer Chiffon, Faux Ostrich Feathers, Silk Satin sash.',
                'image' => 'r2.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Grand Rosette Couture',
                'description' => 'A high-fashion statement piece featuring a dramatic cathedral-length train composed entirely of 3D fabric rosettes. The sleeves are tiered ruffles, creating a voluminous and royal silhouette fit for a main event or editorial shoot.',
                'price' => 18500.00,
                'material' => 'Premium Organza, Heavy Bridal Tulle, Structured Crinoline (for volume).',
                'image' => 'r3.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Enchanted Garden Train',
                'description' => 'A masterpiece of craftsmanship, this robe features climbing 3D floral vines that extend from the hem up the sheer train. The illusion back and bell sleeves give it a fairy-tale aesthetic.',
                'price' => 22000.00,
                'material' => 'Illusion Tulle, 3D Silk Flower Appliqués, Embroidery Thread.',
                'image' => 'r4.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Old Hollywood Glamour',
                'description' => 'Inspired by the Golden Age of cinema, this floor-length satin robe features dramatic, oversized feather sleeves that cascade down the arms. It is paired with a matching lace-trimmed slip for ultimate luxury.',
                'price' => 8200.00,
                'material' => 'Sheer Chiffon, Faux Ostrich Feathers, Silk Satin sash.',
                'image' => 'r5.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Classic Opulence',
                'description' => 'A timeless floor-length robe in pure white satin. The design focuses on clean lines and elegance, accented solely by thick, fluffy feather cuffs at the wrist for a touch of softness.',
                'price' => 4500.00,
                'material' => 'High-Gloss Satin, Marabou Feathers.',
                'image' => 'r6.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Vintage Vogue Sheer ',
                'description' => 'A mid-length robe made from textured burnout fabric (sheer with opaque patterns). It features vintage-style feather cuffs, making it a perfect overlay for bridal lingerie or swimwear.',
                'price' => 3800.00,
                'material' => 'Burnout Chiffon/Velvet, Synthetic Feathers.',
                'image' => 'r7.webp',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Modern Minimalist',
                'description' => 'A sleek and chic short robe with wide bell sleeves. This design eschews lace and feathers for a sophisticated, architectural look that highlights the drape of the fabric.',
                'price' => 2200.00,
                'material' => 'Heavy Silk Satin or Crepe de Chine.',
                'image' => 'r8.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Midnight Chic Ensemble',
                'description' => 'A playful knee-length robe with matching feather cuffs. The set includes a slip with a structured lace bustier, blending comfort with a sexy, party-ready vibe.',
                'price' => 3200.00,
                'material' => 'Polyester Satin, Lace, Feather Trim.',
                'image' => 'r9.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => 'Drama Sleeve Mini',
                'description' => 'A unique mixed-media design featuring a smooth satin body contrasted by massive, ruffled organza sleeves. The sleeves add architectural volume while the short length keeps it flirty and youthful.',
                'price' => 2800.00,
                'material' => 'Duchess Satin (Body), Crystal Organza (Sleeves).',
                'image' => 'r10.jpg',
                'category' => 'robes',
                'stock' => 100,
            ],
            [
                'name' => '"Timeless Grace" Lace Ballgown',
                'description' => 'A classic princess ballgown silhouette with an off-shoulder neckline and sheer long lace sleeves. The bodice is structured and fitted, transitioning into a grand, full skirt. The entire gown is overlaid with delicate, textured lace, giving it a soft and romantic finish without heavy beading.',
                'price' => 85000.00,
                'material' => 'Alençon Lace overlay, Tulle layers, Crinoline for volume.',
                'image' => 'p-1.webp',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => 'Classic Wedding Dress',
                'description' => 'A highly glamorous mermaid silhouette featuring an off-shoulder neckline and sheer long sleeves embellished with lace. The gown is defined by its dramatic versatility, showcasing a fitted lace bodice paired with a voluminous, detachable satin and tulle overskirt that creates a grand train. The entire dress sparkles with intricate beadwork and sequin detailing throughout the fabric.',
                'price' => 95000.00,
                'material' => 'Beaded Lace, Sparkle Tulle, Duchess Satin (overskirt/waistband).',
                'image' => 'p-3.webp',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => '"Victorian Elegance" High-Neck Gown',
                'description' => 'A sophisticated gown that blends vintage modesty with modern allure, featuring a high illusion neckline and long sheer sleeves. The bodice creates a corset effect with a nude lining that highlights the intricate, large-scale floral lace pattern. The silhouette is a fitted mermaid cut that flares gently at the knees, extending into a scalloped lace train.',
                'price' => 68000.00,
                'material' => 'Venise or Guipure Lace, Illusion Mesh, Nude Crepe lining.',
                'image' => 'p-2.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => '"Sleek Avant-Garde" Satin Gown',
                'description' => 'A modern, chic design featuring a pristine, strapless structured bodice with a crisp sweetheart neckline. The skirt is voluminous but features a daring high thigh slit, adding a contemporary edge to the traditional satin look. It is styled with detached, sheer lace long sleeves (gloves) that add a delicate textural contrast to the smooth gown.',
                'price' => 58000.00,
                'material' => 'Mikado or Duchess Satin, Chantilly Lace (sleeves).',
                'image' => 'p-5.webp',
                'category' => 'dresses',
                'stock' => 100,
            ],
            [
                'name' => '""Romantic Whisper" Bustier Gown',
                'description' => 'A soft, lingerie-inspired gown featuring an exposed corset bustier with visible boning channels and lace cups. It has off-shoulder long sleeves made of sheer lace. The skirt is gathered and airy, crafted from layers of soft lace and tulle that drape effortlessly.',
                'price' => 42000.00,
                'material' => 'French Lace, Bobbinet Tulle, Structural Boning.',
                'image' => 'p-6.webp',
                'category' => 'dresses',
                'stock' => 100,
            ],

            [
                'name' => '"Boho Summer" Cold-Shoulder Gown',
                'description' => 'Designed for the free-spirited bride, this gown features spaghetti straps paired with cold-shoulder lace flutter sleeves. The bodice boasts a unique crochet-style lace pattern with a deep V-neck, transitioning into a simple, lightweight pleated skirt that moves freely with the wind.',
                'price' => 32000.00,
                'material' => 'Crochet/Venise Lace, Georgette Crepe, Chiffon.',
                'image' => 'pp-3.jpg',
                'category' => 'dresses',
                'stock' => 100,
            ],



        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
